<?php
include("precedence/classes/cls-connection.php");
$page = ""; 
$meta_title="Privacy Policy - Towards Chem and Materials";
$meta_keyword="Privacy Policy, Policy for Clients, Policy for Visitors";
$meta_description="Discover Privacy Policy Statements by Towards Chem and Materials";
?>
<?php include("header.php");?>
<div class="ptb privacy">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="ttl pb-4 purple-txt">Privacy Policy</h1>
                <p class="para">
                    Towards Chem and Materials ("we," "our," or "us") is committed to safeguarding your privacy. This privacy policy page explains how we collect, use, disclose, 
                    and protect your personal information. By visiting our website and using our services, you consent to the practices described in this Privacy Policy.
                    We value your trust and prioritize the protection of your personal information. 
                </p>
                <h2 class="pt-3">Information collection and use </h2>
                
                <p class="para">We may collect the following types of information when you interact with our website and services: </p>
                <ul class="return-policy-css">
                    <li class="para">Contact information, such as your name, email address, phone number, and postal address.</li>
                    <li class="para">Information you provide when you communicate with us, such as through contact forms or emails.</li>
                </ul>
                <h2 class="pt-3">Your choices</h2>
                
                <p class="para">
                    You can manage your information preferences, including opting out of marketing communications, by contacting us at 
                    <a href="mailto:sales@towardschemandmaterials.com.com">sales@towardschemandmaterials.com.com </a>You can also review and update your personal information by contacting us. 
                </p>
                
                <h2 class="pt-3">Log data </h2>
                
                <p class="para">
                    When you visit our website or use our services, our servers automatically collect log data. This information is generated by your device as it 
                    interacts with our website or services. We use various technologies, including cookies and web server logs, to collect this data. Log data is 
                    valuable for diagnosing technical issues and errors that may arise when using our website. It enables us to address and resolve these issues promptly. 
                </p>
                
                <h2 class="pt-3">Communications </h2>
                 
                <p class="para">
                    We may use your Personal Information to contact you with newsletters, marketing or promotional materials and other information that might interest you. 
                    You can subscribe to the newsletters; however, you can unsubscribe to them by following the instructions given at the bottom of the emails. 
                    We can contact you on the email addresses/ phone numbers provided by you while filling out the contact-us form and this information can be updated 
                    from time to time by emailing at <a href="mailto:sales@towardschemandmaterials.com.com">sales@towardschemandmaterials.com.com </a> 
                </p>
                
               
                <h2 class="pt-3">Cookies </h2>
               
                <p class="para">
                    We use cookies and similar technologies to enhance your online experience. We use these cookies to collect information about how visitors use our
                    website. They help us understand which pages are most popular, how visitors move around the site, and whether they encounter any errors. This data
                    is used to improve our website and enhance your experience. You can control cookie settings in your browser, please note that disabling cookies may 
                    affect your ability to access certain features of our website. 
                </p>
                
                <h2 class="pt-3">Security</h2>
                <p class="para">
                    Ensuring the security and protection of your personal information is a top priority at Towards Chem and Materials. We are dedicated to implementing robust security measures to safeguard your data. This section outlines our commitment to maintaining the security of your personal information. 
                </p>
                <ul class="return-policy-css">
                    <li class="para">
                        Access to your personal information is restricted to authorized personnel who require access to perform their duties. 
                    </li>
                    <li class="para">
                        All of our employees receive training in data security and privacy practices. We emphasize the importance of handling personal information with 
                        care and confidentiality. Our staff is educated in how to recognize and respond to security incidents.
                    </li>
                    <li class="para">
                        Our systems are continuously monitored for security threats, and we maintain intrusion detection and prevention systems. 
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php include("footer.php");?>